//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vizeprojeEntities : DbContext
    {
        public vizeprojeEntities()
            : base("name=vizeprojeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tab_Admin> Tab_Admin { get; set; }
        public virtual DbSet<Tab_Dersler> Tab_Dersler { get; set; }
        public virtual DbSet<Tab_Kulupler> Tab_Kulupler { get; set; }
        public virtual DbSet<Tab_Notlar> Tab_Notlar { get; set; }
        public virtual DbSet<Tab_Ogrenciler> Tab_Ogrenciler { get; set; }
        public virtual DbSet<Tab_Ogretmenler> Tab_Ogretmenler { get; set; }
    }
}
