//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Dersler
    {
        public int Dersid { get; set; }
        public string Dersad { get; set; }
    }
}
