//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje1.Models.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Tab_Ogrenciler
    {
        public int Ogrid { get; set; }
        public string Ograd { get; set; }
        public string Ogrsoyad { get; set; }
        public string OgrResim { get; set; }
        public string OgrCinsiyet { get; set; }

        // Tab_Kulupler sýnýfýna referans veren özellik
        public int OgrKulupid { get; set; }
        public Tab_Kulupler Tab_Kulupler { get; set; }
    }
}