//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Kulupler
    {
        public int OgrKulupid { get; set; }
        public string OgrKulupad { get; set; } // Eksik olan özellik
        public string Ogkulupkont { get; set; }
    }
}
