//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Notlar
    {
        public int NotIid { get; set; }
        public string Dersad { get; set; }
        public string ograd { get; set; }
        public string sınav1 { get; set; }
        public string sınav2 { get; set; }
        public string sınav3 { get; set; }
        public string ortalama { get; set; }
        public string durum { get; set; }
        public string proje { get; set; }
    }
}
