//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Ogretmenler
    {
        public int Ogrtid { get; set; }
        public string Ogrtad { get; set; }
        public string Ogrtsoyad { get; set; }
        public string Ogrtbolum { get; set; }
        public string Ogrtders { get; set; }
    }
}
